server:
  port: 8090

spring:
  application:
    name: msvc-studen

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/courseDB
    username: root
    password: 45549813O

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    databaseeureka:
      instance:
        hostname: localhost
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
      -platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http://localhost:8888



